# Generated by Django 3.0.2 on 2020-02-10 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_auto_20191122_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPaymentsTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment_gateway.Transaction')),
                ('TransactionId', models.IntegerField(db_index=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Currency', models.CharField(max_length=3)),
                ('DateTime', models.DateTimeField()),
                ('CardFirstSix', models.CharField(max_length=6)),
                ('CardLastFour', models.CharField(max_length=4)),
                ('CardType', models.CharField(max_length=5)),
                ('CardExpDate', models.CharField(max_length=6)),
                ('TestMode', models.BooleanField()),
                ('Status', models.CharField(max_length=32)),
                ('OperationType', models.CharField(max_length=16)),
                ('AccountId', models.CharField(blank=True, max_length=64, null=True)),
                ('SubscriptionId', models.CharField(blank=True, max_length=64, null=True)),
                ('TokenRecipient', models.CharField(blank=True, max_length=128, null=True)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('IpAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('IpCountry', models.CharField(blank=True, max_length=2, null=True)),
                ('IpCity', models.CharField(blank=True, max_length=128, null=True)),
                ('IpRegion', models.CharField(blank=True, max_length=128, null=True)),
                ('IpDistrict', models.CharField(blank=True, max_length=128, null=True)),
                ('Issuer', models.CharField(blank=True, max_length=128, null=True)),
                ('IssuerBankCountry', models.CharField(blank=True, max_length=2, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('GatewayName', models.CharField(blank=True, max_length=128, null=True)),
                ('Token', models.CharField(blank=True, max_length=128, null=True)),
                ('TotalFee', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'cloudpayments transaction',
                'verbose_name_plural': 'cloudpayments transactions',
            },
            bases=('payment_gateway.transaction',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DUMMY'), (1, 'WALLETONE'), (2, 'CLOUDPAYMENTS')], verbose_name='type'),
        ),
    ]